name: Coverage, Versioning & Deployment

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: "Unit Test Coverage"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config cmake
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov

      - name: Run cargo llvm-cov
        run: |
          cargo llvm-cov --ignore-filename-regex main.rs --lcov --output-path target/lcov.info --workspace

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  versioning:
    name: "Versioning & Crates.io Deployment"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            @semantic-release/commit-analyzer@11.1.0
            @semantic-release/release-notes-generator@12.1.0
            @semantic-release/github@9.2.6
            @semantic-release-cargo/semantic-release-cargo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}