name: Coverage, Versioning & Deployment

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: "Unit Test Coverage"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config cmake
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov

      - name: Run cargo llvm-cov
        run: |
          cargo llvm-cov --ignore-filename-regex main.rs --lcov --output-path target/lcov.info --workspace

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  versioning:
    name: "Versioning & Crates.io Deployment"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10'

      - name: Install Dependencies
        run: npm install

      - name: Semantic Release
        run: | 
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          export CARGO_REGISTRY_TOKEN=${{ secrets.CARGO_TOKEN }}
          npx semantic-release --repository-url https://github.com/Jamesmallon1/solana-block-cacher.git --GH_TOKEN ${{ secrets.GH_TOKEN }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}