name: Build, Versioning, Testing & Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build Pipeline"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Rust & Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Application
        run: |
          cargo build --release

  testing:
    name: "Unit Tests"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Rust & Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run Unit Tests
        run: |
          cargo test